# Generated by Django 4.2.2 on 2023-06-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionPlace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
