# Generated by Django 4.2 on 2023-06-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionPlace', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
